In [1]:
import numpy as np

# Define a matrix
matrix = np.array([[0.243, 3, 9],
                   [4.7, 8.23, 6],
                   [7, 8, 9]])

# Find the minimum and maximum values in the matrix
min_value = np.min(matrix)
max_value = np.max(matrix)

# Calculate the "opposite" values for each element
opposite_matrix = (max_value + min_value) - matrix

print("Original Matrix:")
print(matrix)

print("\nOpposite Matrix:")
print(opposite_matrix)

Original Matrix:
[[0.243 3.    9.   ]
 [4.7   8.23  6.   ]
 [7.    8.    9.   ]]

Opposite Matrix:
[[9.    6.243 0.243]
 [4.543 1.013 3.243]
 [2.243 1.243 0.243]]


In [2]:
fmatrix = matrix.flatten()
fmatrix

array([0.243, 3.   , 9.   , 4.7  , 8.23 , 6.   , 7.   , 8.   , 9.   ])

In [3]:
rf_matrix = fmatrix[::-1]
rf_matrix

array([9.   , 8.   , 7.   , 6.   , 8.23 , 4.7  , 9.   , 3.   , 0.243])

In [4]:
rf_matrix.reshape(matrix.shape)

array([[9.   , 8.   , 7.   ],
       [6.   , 8.23 , 4.7  ],
       [9.   , 3.   , 0.243]])

In [5]:
import pandas as pd

In [6]:
clr_df = pd.read_csv('./clr_network_for_distances.csv')

In [7]:
clr_df.rename(columns={'Unnamed: 0':'TTHERM_ID'}, inplace=True)

In [8]:
clr_df.shape

(20326, 20327)

In [9]:
clr_df.head()

TTHERM_ID  TTHERM_000000042  TTHERM_000000045  TTHERM_00000010  \
0  TTHERM_000000042          0.000000          0.000000         0.752140   
1  TTHERM_000000045          0.000000          0.000000         2.419513   
2   TTHERM_00000010          0.752140          2.419513         0.000000   
3   TTHERM_00000020          2.351691          0.000000         4.752502   
4   TTHERM_00000030          0.766892          0.000000         2.560668   

   TTHERM_00000020  TTHERM_00000030  TTHERM_00000040  TTHERM_00000070  \
0         2.351691         0.766892         0.000000         2.450125   
1         0.000000         0.000000         0.000000         0.000000   
2         4.752502         2.560668         0.000000         0.406447   
3         0.000000         5.771229         1.423059         0.072651   
4         5.771229         0.000000         2.146661         0.000000   

   TTHERM_000001189  TTHERM_000001241  ...  TTHERM_02091560  TTHERM_02094560  \
0          2.047900               0.0  ...         0.000000              0.0   
1          0.000000               0.0  ...         0.000000              0.0   
2          1.138716               0.0  ...         0.000000              0.0   
3          1.300164               0.0  ...         0.801577              0.0   
4          1.689063               0.0  ...         0.327724              0.0   

   TTHERM_02096560  TTHERM_02105572  TTHERM_02272860  TTHERM_02293890  \
0         0.000000              0.0              0.0         0.000000   
1         0.000000              0.0              0.0         1.955770   
2         0.225795              0.0              0.0         0.510083   
3         0.000000              0.0              0.0         0.000000   
4         0.000000              0.0              0.0         0.000000   

   TTHERM_02385080  TTHERM_02555200  TTHERM_02607240  TTHERM_02653470  
0         0.000000              0.0              0.0         0.000000  
1         0.000000              0.0              0.0         0.706766  
2         0.245607              0.0              0.0         1.327470  
3         0.000000              0.0              0.0         0.000000  
4         0.000000              0.0              0.0         0.000000  

[5 rows x 20327 columns]

In [10]:
max_zscore = clr_df.max(axis=None, numeric_only=True)
max_zscore

52.9604085486791

In [11]:
min_zscore = clr_df.min(axis=None, numeric_only=True)
min_zscore

0.0

In [12]:
zscore_arr = clr_df.loc[:,clr_df.columns[1:]].to_numpy()
zscore_arr

array([[0.        , 0.        , 0.75213975, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 2.41951306, ..., 0.        , 0.        ,
        0.70676605],
       [0.75213975, 2.41951306, 0.        , ..., 0.        , 0.        ,
        1.32747021],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.73858538,
        1.1887816 ],
       [0.        , 0.        , 0.        , ..., 2.73858538, 0.        ,
        0.        ],
       [0.        , 0.70676605, 1.32747021, ..., 1.1887816 , 0.        ,
        0.        ]])

In [13]:
inverted_zscore_arr = (max_zscore + min_zscore) - zscore_arr

In [14]:
inverted_zscore_arr

array([[52.96040855, 52.96040855, 52.2082688 , ..., 52.96040855,
        52.96040855, 52.96040855],
       [52.96040855, 52.96040855, 50.54089548, ..., 52.96040855,
        52.96040855, 52.2536425 ],
       [52.2082688 , 50.54089548, 52.96040855, ..., 52.96040855,
        52.96040855, 51.63293833],
       ...,
       [52.96040855, 52.96040855, 52.96040855, ..., 52.96040855,
        50.22182317, 51.77162695],
       [52.96040855, 52.96040855, 52.96040855, ..., 50.22182317,
        52.96040855, 52.96040855],
       [52.96040855, 52.2536425 , 51.63293833, ..., 51.77162695,
        52.96040855, 52.96040855]])

In [15]:
inverted_zscore_arr.shape

(20326, 20326)

In [16]:
np.min(inverted_zscore_arr)

0.0

In [17]:
(inverted_zscore_arr.shape[0] * inverted_zscore_arr.shape[1]) - np.count_nonzero(inverted_zscore_arr)

2

In [18]:
zero_idxs = np.where(inverted_zscore_arr == 0)

In [22]:
zero_idxs

(array([4301, 7544]), array([7544, 4301]))

In [19]:
import copy

nonzero_inverted_zscore_arr = copy.deepcopy(inverted_zscore_arr)

In [20]:
for idx_pair in zero_idxs:
    nonzero_inverted_zscore_arr[idx_pair[0]][idx_pair[1]] = 1e-20

In [21]:
np.where(nonzero_inverted_zscore_arr == 0)

(array([], dtype=int64), array([], dtype=int64))